### ISSUE TITLE
Plot frames missing

### ISSUE THREAD

**Issue by ro-ble** [JuliaPlots/MakieThemes.jl#14]
When using your theme package, I noticed that the frame as you can see on the left and bottom of the plot is missing.

![image](https://user-images.githubusercontent.com/31608174/77773086-6a813e80-7049-11ea-8b04-ca73924a9d19.png)
_without frame_

![image](https://user-images.githubusercontent.com/31608174/77771565-22611c80-7047-11ea-8bd5-53adcac51ede.png)
_with frame (like intended)_

When searching for the source of this problem I saw that the frames attribute was properly set on the axis2d object. However that did not result in the wanted frame. 

I found out, that setting the frames attribute on the axis object instead of the axis2d would produce our frame. Do you know if this would be an AbstractPlotting Error or something to correct in your Package?

following code did the quick fix:
```
import MakieThemes
const mt = MakieThemes
t = mt.ggthemr(:fresh)
t.axis.frame.frames = t.axis2d.frame.frames
```

**Comment by mkborregaard** [comment]
Yes, this package is not currently fully functional. Aim to make it so soon!

**Comment by ro-ble** [comment]
I really appreciate your work. If you wish some help with this, you can message me.

**Comment by mkborregaard** [comment]
Thanks, very appreciated. I'll be in touch once I get an overview :-)
