### ISSUE TITLE
Example doesnt work or I'm too stupid

### ISSUE THREAD

**Issue by drhouse82** [JuliaPlots/MakieThemes.jl#15]
I tried this code: 
```
using Makie
using MakieThemes
show_ggthemr(:fresh)
```
and get this output:
![Untitled](https://user-images.githubusercontent.com/16007263/87879316-2ea02980-c9ea-11ea-90e7-ed12c58803e7.png)

I suppose this is not meant to be like that, but should be more colorful as indicated on 
https://github.com/JuliaPlots/MakieThemes.jl

Any ideas? I'm on julia 1.4 on windows 10.
```
Julia Version 1.4.2
Commit 44fa15b150* (2020-05-23 18:35 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = "C:\Users\joach\AppData\Local\Programs\Microsoft VS Code\Code.exe"
  JULIA_NUM_THREADS = 8
```

**Comment by mkborregaard** [comment]
You're right, the package is broken - I'll update the readme
